//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Auth0.ClientSide.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.Auth0.ClientSide.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        internal static string ApplicationJsonMediaType {
            get {
                return ResourceManager.GetString("ApplicationJsonMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;use strict&quot;;
        ///
        ///if (window.opener &amp;&amp; window.name === &quot;auth0_signup_popup&quot;) {
        ///    window.opener.___blazor_auth0.popupCallback(window.location.href);
        ///    close();
        ///}else{
        ///	window.___blazor_auth0 = {
        ///		logOut: (src) =&gt; {
        ///			&quot;use strict&quot;;
        ///			return new Promise((resolve) =&gt; {
        ///				let iframe = document.createElement(&quot;iframe&quot;);
        ///				iframe.setAttribute(&quot;src&quot;, src);
        ///				iframe.style.display = &quot;none&quot;;
        ///				document.body.appendChild(iframe);
        ///				iframe.onload = () =&gt; {                
        ///					document.body.re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClientSideJs {
            get {
                return ResourceManager.GetString("ClientSideJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must indicate either the SECRET when using Authorization Code or the CODE_VERIFIER when using Authorization Code with PKCE, you&apos;re providing both..
        /// </summary>
        internal static string DuplicatedPKCERequiredParamError {
            get {
                return ResourceManager.GetString("DuplicatedPKCERequiredParamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ___blazor_auth0.
        /// </summary>
        internal static string InteropElementName {
            get {
                return ResourceManager.GetString("InteropElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid access token hash.
        /// </summary>
        internal static string InvalidAccessTokenHashError {
            get {
                return ResourceManager.GetString("InvalidAccessTokenHashError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid_hash: response_type contains `token`, but the parsed hash does not contain an `access_token` property.
        /// </summary>
        internal static string InvalidHashMissingAccessTokenError {
            get {
                return ResourceManager.GetString("InvalidHashMissingAccessTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid_hash: response_type contains `id_token`, but the parsed hash does not contain an `id_token` property.
        /// </summary>
        internal static string InvalidHashMissingIdTokenError {
            get {
                return ResourceManager.GetString("InvalidHashMissingIdTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Nonce.
        /// </summary>
        internal static string InvalidNonceError {
            get {
                return ResourceManager.GetString("InvalidNonceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must indicate either the SECRET when using Authorization Code or the CODE_VERIFIER when using Authorization Code with PKCE, both values are missing..
        /// </summary>
        internal static string MissingPKCERequiredParamError {
            get {
                return ResourceManager.GetString("MissingPKCERequiredParamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: No at_hash claim was present in the id_token..
        /// </summary>
        internal static string NotAltChashWarning {
            get {
                return ResourceManager.GetString("NotAltChashWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be null.
        /// </summary>
        internal static string NullArgumentExceptionError {
            get {
                return ResourceManager.GetString("NullArgumentExceptionError", resourceCulture);
            }
        }
    }
}
